package com.bank.bian.fraudresolution;

import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.info.Info;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;

/**
 * BIAN Service Domain: Fraud Resolution
 *
 * Business Area:      Risk and Compliance
 * Business Domain:    Financial Crime
 * Functional Pattern: Process
 * Asset Type:         Fraud Resolution
 * Control Record:     Fraud Resolution Procedure
 *
 * Generated by the bian-platform service generator (Phase 1 — shallow build).
 * Replace the in-memory store with real persistence and domain logic in Phase 2.
 */
@SpringBootApplication
public class Application {

    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }

    @Bean
    public OpenAPI openApi() {
        return new OpenAPI().info(new Info()
                .title("Fraud Resolution — BIAN Semantic API")
                .description("Service Domain 'Fraud Resolution' (Process pattern) "
                        + "operating on the 'Fraud Resolution Procedure' control record.")
                .version("0.1.0"));
    }
}
