apiVersion: v2
name: sd-fraud-resolution
description: "BIAN Service Domain: Fraud Resolution (Process pattern, Risk and Compliance)"
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - bian
  - process
annotations:
  bian/business-area: "Risk and Compliance"
  bian/business-domain: "Financial Crime"
  bian/asset-type: "Fraud Resolution"
  bian/control-record: "Fraud Resolution Procedure"
